/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdRouteImport } from './routes/$id'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSharesRouteImport } from './routes/api/shares'
import { Route as ApiSharesIdRouteImport } from './routes/api/shares.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesRoute = ApiSharesRouteImport.update({
  id: '/api/shares',
  path: '/api/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesIdRoute = ApiSharesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSharesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/api/shares/$id': typeof ApiSharesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/api/shares/$id': typeof ApiSharesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/api/shares/$id': typeof ApiSharesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$id' | '/api/health' | '/api/shares' | '/api/shares/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$id' | '/api/health' | '/api/shares' | '/api/shares/$id'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/api/health'
    | '/api/shares'
    | '/api/shares/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSharesRoute: typeof ApiSharesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares': {
      id: '/api/shares'
      path: '/api/shares'
      fullPath: '/api/shares'
      preLoaderRoute: typeof ApiSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares/$id': {
      id: '/api/shares/$id'
      path: '/$id'
      fullPath: '/api/shares/$id'
      preLoaderRoute: typeof ApiSharesIdRouteImport
      parentRoute: typeof ApiSharesRoute
    }
  }
}

interface ApiSharesRouteChildren {
  ApiSharesIdRoute: typeof ApiSharesIdRoute
}

const ApiSharesRouteChildren: ApiSharesRouteChildren = {
  ApiSharesIdRoute: ApiSharesIdRoute,
}

const ApiSharesRouteWithChildren = ApiSharesRoute._addFileChildren(
  ApiSharesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSharesRoute: ApiSharesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
